# Generated by Django 5.2.5 on 2025-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('business', 'Business Owner'), ('advertiser', 'Advertiser')], default='business', max_length=20),
        ),
    ]
