# Generated by Django 5.2.5 on 2026-03-31 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_registrationotp_user_address_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('business', 'Business Owner'), ('advertiser', 'Advertiser')], default='advertiser', max_length=20),
        ),
        migrations.CreateModel(
            name='BanAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_text', models.TextField(help_text="The user's appeal message")),
                ('admin_response', models.TextField(blank=True, help_text='Message from the superadmin', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('rejected', 'Appeal Rejected'), ('approved', 'Appeal Approved - Unbanned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
