# Generated by Django 5.2.5 on 2026-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Receive email notifications for bookings, billboards, and account events'),
        ),
    ]
