# Generated by Django 5.2.5 on 2025-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base rate per day', max_digits=10),
        ),
        migrations.AddField(
            model_name='billboard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
