# Generated by Django 5.2.5 on 2026-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0002_billboard_daily_rate_billboard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='billboards/'),
        ),
    ]
