# Generated by Django 5.2.5 on 2026-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0003_billboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='pending', max_length=20),
        ),
    ]
