# Generated by Django 5.2.5 on 2026-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0004_alter_billboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Feedback from super admin for improvements', null=True),
        ),
    ]
