# Generated by Django 5.2.5 on 2026-03-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0005_billboard_admin_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboard',
            name='admin_remarks',
        ),
        migrations.AddField(
            model_name='billboard',
            name='feedback_message',
            field=models.TextField(blank=True, help_text='Message from Admin when requesting changes', null=True),
        ),
    ]
