# Generated by Django 5.2.5 on 2026-03-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0006_remove_billboard_admin_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='billboard_documents/')),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='billboards.billboard')),
            ],
        ),
    ]
