# Generated by Django 5.2.5 on 2026-03-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0008_billboardreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='location_tier',
            field=models.CharField(choices=[('standard', 'Standard (1.0x)'), ('prime', 'Prime (1.5x)'), ('ultra', 'Ultra-Prime (2.0x)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='billboard',
            name='weekend_multiplier',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Multiplier for weekend pricing (default 0.80)', max_digits=4),
        ),
    ]
