# Generated by Django 5.2.5 on 2026-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0009_billboard_location_tier_billboard_weekend_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='booking_lead_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='Minimum days in advance a booking must be made'),
        ),
    ]
