# Generated by Django 5.2.5 on 2026-01-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='frequency_per_hour',
            field=models.IntegerField(default=10, help_text='Number of times ad is shown per hour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_duration_seconds',
            field=models.IntegerField(choices=[(10, '10 Seconds'), (15, '15 Seconds'), (20, '20 Seconds'), (30, '30 Seconds'), (45, '45 Seconds'), (60, '60 Seconds')], default=10),
        ),
    ]
