# Generated by Django 5.2.5 on 2026-02-04 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_booking_frequency_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('active', 'Active')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='creative_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='frequency_per_hour',
            field=models.IntegerField(default=10, help_text='Number of times ad is shown per hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot_duration_seconds',
            field=models.IntegerField(default=10, help_text='Duration in seconds (5-120)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
