# Generated by Django 5.2.5 on 2026-02-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='campaigns.booking')),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('booking', 'date', 'hour')},
            },
        ),
    ]
