# Generated by Django 5.2.5 on 2026-02-12 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_bookingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='frequency_per_hour',
            field=models.IntegerField(default=10, help_text='Custom frequency for this specific hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
