# Generated by Django 5.2.5 on 2026-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_bookingslot_frequency_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for payment after approval', null=True),
        ),
    ]
