# Generated by Django 5.2.5 on 2026-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_add_booking_lead_days_and_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net amount payable to billboard owner (price_calculated - vat_amount)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT portion (13%) reverse-extracted from price_calculated on payment', max_digits=12, null=True),
        ),
    ]
