# Generated by Django 5.2.5 on 2026-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_add_vat_and_payout_to_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform commission (5% of base amount after VAT)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net amount payable to billboard owner (base_amount - platform_commission)', max_digits=12, null=True),
        ),
    ]
